import { Book, Genre } from './types';

export const genres: Genre[] = [
  { name: 'Fiction', slug: 'fiction' },
  { name: 'Mystery', slug: 'mystery' },
  { name: 'Thriller', slug: 'thriller' },
  { name: 'Romance', slug: 'romance' },
  { name: 'Science Fiction', slug: 'science-fiction' },
  { name: 'Fantasy', slug: 'fantasy' },
];

export const books: Book[] = [
  {
    id: '1',
    title: 'The Whispering Woods',
    author: 'Elara Vance',
    authorBio: 'Elara Vance is a bestselling author known for her enchanting fantasy novels that transport readers to magical realms.',
    price: 9.99,
    rating: 4.5,
    ratingsCount: 1250,
    summary: 'In a forest that whispers secrets to those who listen, a young woman discovers she is the key to an ancient prophecy. A tale of magic, courage, and destiny.',
    coverImageId: 'cover-1',
    genre: 'Fantasy',
  },
  {
    id: '2',
    title: 'Echoes of Neptune',
    author: 'Jaxom Ryder',
    authorBio: 'Jaxom Ryder pens thrilling science fiction adventures, exploring the vastness of space and the human condition.',
    price: 12.99,
    rating: 4.7,
    ratingsCount: 2340,
    summary: 'A derelict starship is found adrift near Neptune, its crew vanished. A lone investigator must uncover the chilling truth behind their disappearance before it\'s too late.',
    coverImageId: 'cover-2',
    genre: 'Science Fiction',
  },
  {
    id: '3',
    title: 'The Crimson Bloom',
    author: 'Isabella Dubois',
    authorBio: 'Isabella Dubois writes passionate and intricate romance novels that have captured the hearts of readers worldwide.',
    price: 7.99,
    rating: 4.3,
    ratingsCount: 3400,
    summary: 'Amidst the backdrop of 19th-century Paris, a fiery painter and a stoic nobleman find their lives intertwined in a story of forbidden love and sacrifice.',
    coverImageId: 'cover-3',
    genre: 'Romance',
  },
  {
    id: '4',
    title: 'The Shadow in the Alley',
    author: 'Arthur Finch',
    authorBio: 'Arthur Finch is a master of the mystery genre, crafting complex plots and unforgettable detectives.',
    price: 11.99,
    rating: 4.8,
    ratingsCount: 5120,
    summary: 'When a renowned detective finds a cryptic note at a crime scene, he\'s pulled into a cat-and-mouse game with a killer who is always one step ahead.',
    coverImageId: 'cover-4',
    genre: 'Mystery',
  },
  {
    id: '5',
    title: 'The Last Stand',
    author: 'Cole Matthews',
    authorBio: 'Cole Matthews is an acclaimed author of heart-pounding thrillers that keep readers on the edge of their seats.',
    price: 14.99,
    rating: 4.6,
    ratingsCount: 4200,
    summary: 'An ex-special forces operative is forced back into action when a terrorist group takes a city hostage. It\'s a race against time where one wrong move could be fatal.',
    coverImageId: 'cover-5',
    genre: 'Thriller',
  },
  {
    id: '6',
    title: 'A River of Stars',
    author: 'Seraphina Lin',
    authorBio: 'Seraphina Lin writes beautiful and poignant fiction that explores themes of family, loss, and resilience.',
    price: 8.99,
    rating: 4.4,
    ratingsCount: 1890,
    summary: 'Three generations of women navigate their complex relationships and shared history, discovering that the bonds of family are as enduring as the stars.',
    coverImageId: 'cover-6',
    genre: 'Fiction',
  },
  {
    id: '7',
    title: 'The Gilded Cage',
    author: 'Julian Croft',
    authorBio: 'Julian Croft is known for his atmospheric mysteries set in the dark, foggy streets of Victorian London.',
    price: 10.99,
    rating: 4.5,
    ratingsCount: 2200,
    summary: 'A series of impossible thefts from London\'s wealthiest families baffles Scotland Yard. Is it a master thief, or is something more supernatural at play?',
    coverImageId: 'cover-7',
    genre: 'Mystery',
  },
  {
    id: '8',
    title: 'Dragon\'s Heir',
    author: 'Elara Vance',
    authorBio: 'Elara Vance is a bestselling author known for her enchanting fantasy novels that transport readers to magical realms.',
    price: 13.99,
    rating: 4.9,
    ratingsCount: 6800,
    summary: 'The long-lost heir to a draconic throne must reclaim their birthright from a usurper, with the help of a band of loyal knights and ancient magic.',
    coverImageId: 'cover-8',
    genre: 'Fantasy',
  },
  {
    id: '9',
    title: 'Cybernetic Dawn',
    author: 'Jaxom Ryder',
    authorBio: 'Jaxom Ryder pens thrilling science fiction adventures, exploring the vastness of space and the human condition.',
    price: 12.99,
    rating: 4.6,
    ratingsCount: 3150,
    summary: 'In a future where humans and AI coexist, a detective must solve a murder where the prime suspect is an artificial intelligence that claims innocence.',
    coverImageId: 'cover-9',
    genre: 'Science Fiction',
  },
  {
    id: '10',
    title: 'Love in the Lavender Fields',
    author: 'Isabella Dubois',
    authorBio: 'Isabella Dubois writes passionate and intricate romance novels that have captured the hearts of readers worldwide.',
    price: 6.99,
    rating: 4.2,
    ratingsCount: 2950,
    summary: 'A city-dweller inherits a lavender farm in Provence and finds not only a new life but also an unexpected romance with a charming local winemaker.',
    coverImageId: 'cover-10',
    genre: 'Romance',
  },
  {
    id: '11',
    title: 'The Silent Witness',
    author: 'Cole Matthews',
    authorBio: 'Cole Matthews is an acclaimed author of heart-pounding thrillers that keep readers on the edge of their seats.',
    price: 13.99,
    rating: 4.7,
    ratingsCount: 4890,
    summary: 'A psychologist treating a patient with amnesia uncovers a conspiracy that puts both their lives in grave danger. The truth is locked in her patient\'s mind.',
    coverImageId: 'cover-11',
    genre: 'Thriller',
  },
  {
    id: '12',
    title: 'The Librarian of Forgotten Books',
    author: 'Seraphina Lin',
    authorBio: 'Seraphina Lin writes beautiful and poignant fiction that explores themes of family, loss, and resilience.',
    price: 9.99,
    rating: 4.6,
    ratingsCount: 3200,
    summary: 'A young librarian discovers a hidden repository of books that were never published and sets out to find their authors, uncovering stories of hope and heartbreak.',
    coverImageId: 'cover-12',
    genre: 'Fiction',
  },
];
